profiles {
  local {
    getPrisonNumberUsers = 1
    getCrnUsers = 1
    getDefendantIdUsers = 1
  }
  worstcase {
    getPrisonNumberUsers = 30
    getCrnUsers = 1
    getDefendantIdUsers = 1
  }
  happypath {
    getPrisonNumberUsers = 15
    getCrnUsers = 1
    getDefendantIdUsers = 1
  }
}