name: Gatling performance test run

on:
  schedule:
    - cron: '0 11 * * 1-5'
  workflow_dispatch:
    inputs:
      envName:
        description: "Which API should this run against"
        required: false
        default: "dev"
        type: choice
        options:
          - dev
      profile:
        description: "Optional Which profile to run."
        required: false
        default: "happypath"
        type: choice
        options:
          - local
          - worstcase
          - happypath
      duration:
        description: "The execution time"
        required: false
        default: "360"
        type: string
jobs:
  gatling-run:
    name: Run Gatling simulations
    runs-on: [ self-hosted, hmpps-github-actions-runner ]
    permissions:
      contents: read
      actions: read
    timeout-minutes: 300
    env:
      CLIENT_ID: ${{ secrets.GATLING_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.GATLING_CLIENT_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up JDK 25
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: '25'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Touch env file
        run: touch .env

      - name: Start Gatling
        env:
          CLIENT_ID: ${{ secrets.GATLING_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.GATLING_CLIENT_SECRET }}
        run: |
         
          PROFILE="${{ github.event.inputs.profile }}"
          ENV="${{ github.event.inputs.envName }}"
          
          set -eo pipefail
          
          CLIENT_ID="${CLIENT_ID}" \
          CLIENT_SECRET="${CLIENT_SECRET}" \
          ./gradlew gatlingRunCi \
          --no-daemon \
          -Dprofile="${{ github.event.inputs.profile }}" \
          -Denv="${{ github.event.inputs.envName }}" \
          -Dduration="${{ github.event.inputs.duration }}"

      - name: Upload Gatling reports
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: gatling-reports
          path: |
            gatling/build/reports/gatling/**
            **/build/reports/gatling/**
          if-no-files-found: warn